### ISSUE TITLE
Ip publica

### ISSUE THREAD

**Issue by ElCaptus** [Sebastian-Toledo/Task-Manager-Frontend#4]
Estas hardcodeando la ip publica.
1- podria llevar a ataques dirigidos.
2- la ip es dinamica, podria cambiar

Solucion: usar https-proxies

**Comment by ElCaptus** [comment]
Otra solucion: usar algun archivo de configuracion que no se vea en el repositorio 😄  (.env/.conf)

**Comment by Sebastian-Toledo** [comment]
Listo, use la del .env, me parecio la mejor para este caso
